version: '3.3'
services:
  mongodb:
    container_name: mongodb
    image: 'mongo:4.0'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db
      - ./mongodump:/dump
  quarkus:
    container_name: quarkus
    image: michelepapale1996/estate-notifier-bot:1.0.0-SNAPSHOT
    restart: always
    user: root
    volumes:
      - ./quarkus_logs:/deployments/logs
    depends_on:
      - mongodb
    ports:
      - 5005:5005
      - 8080:8080